In [345]:
import numpy as np
import pandas as pd

In [346]:
np.random.seed(0)

In [347]:
N = 1000

print(f'Número de observações: {N}')

Número de observações: 1000


In [348]:
K = 2

print(f'Número de categorias latentes: {K}')

Número de categorias latentes: 2


In [349]:
Z = np.random.multinomial(pvals = K*[1/K], n = N)

print('Quantidade de observações por categoria:\n')

print(Z)

Quantidade de observações por categoria:

[502 498]


In [350]:
sigma = 1

mu = np.linspace(start = -3*sigma*K, stop = 3*sigma*K, num = K)

print(f'Variância dos dados: {sigma}\n')

print('Médias de cada categoria latente:\n')

print(mu)

Variância dos dados: 1

Médias de cada categoria latente:

[-6.  6.]


In [351]:
UGMM_Simples = np.zeros(shape = 1)

for k in range(K):

    X = np.random.normal(loc = mu[k], size = Z[k])

    UGMM_Simples = np.hstack((UGMM_Simples, X))

print('Dados Observados (UGMM Simples):\n')

print(np.round(UGMM_Simples, 2))

Dados Observados (UGMM Simples):

[ 0.   -5.02 -3.76 ...  5.64  6.56  6.89]


In [352]:
p = np.random.dirichlet(alpha = K*[1/K])

print('Probabilidades de cada categoria latente:\n')

print(np.round(p, 2))

Probabilidades de cada categoria latente:

[0.65 0.35]


In [353]:
UMMM = np.zeros(shape = 1)

for k in range(K):

    X = np.random.binomial(n = 1, p = p[k], size = Z[k])

    UMMM = np.hstack((UMMM, X))

print('Dados Observados (UMMM):\n')

print(UMMM)

Dados Observados (UMMM):

[0. 1. 1. ... 0. 0. 0.]


In [ ]:
f = np.linspace(start = 1, stop = 3*K, num = K)

print('Frequência de cada categoria latente:\n')

print(np.round(f, 2))

Frequência de cada categoria latente:

[1. 6.]


In [355]:
UPMM = np.zeros(shape = 1)

for k in range(K):

    X = np.random.poisson(lam = f[k], size = Z[k])

    UPMM = np.hstack((UPMM, X))

print('Dados Observados (UPMM):\n')

print(UPMM)

Dados Observados (UPMM):

[0. 1. 3. ... 4. 4. 4.]


In [356]:
pd.DataFrame(UGMM_Simples, columns = ['x_n']).to_csv('Dados\\UGMM_Simples.csv', index =  False)

pd.DataFrame(UMMM, columns = ['x_n']).to_csv('Dados\\UMMM.csv', index =  False)

pd.DataFrame(UPMM, columns = ['x_n']).to_csv('Dados\\UPMM.csv', index =  False)